import React from 'react';
import * as FiIcons from 'react-icons/fi';
import * as AiIcons from 'react-icons/ai';
import * as MdIcons from 'react-icons/md';

export const sidebarList = [
    {
        title: 'Dashboard',
        icon: <AiIcons.AiFillDashboard />,
        path: '/'
    },
    {
        title: 'Customers',
        icon: <FiIcons.FiUsers />,
        path: '/customers'
    },
    {
        title: 'Washing steps',
        icon: <AiIcons.AiOutlineOrderedList />,
        path: '/washing-steps'
    },
    {
        title: 'Washing programs',
        icon: <MdIcons.MdLocalCarWash />,
        path: '/washing-programs'
    },
]

export const washingSteps = [{"id":1,"name":"blacknor0","duration":42,"substance":"Maroon"},
{"id":2,"name":"jbucktharp1","duration":36,"substance":"Red"},
{"id":3,"name":"lbeckhurst2","duration":11,"substance":"Purple"},
{"id":4,"name":"gbroose3","duration":86,"substance":"Violet"},
{"id":5,"name":"dsheriff4","duration":66,"substance":"Goldenrod"},
{"id":6,"name":"dhargreaves5","duration":33,"substance":"Violet"},
{"id":7,"name":"tphear6","duration":99,"substance":"Turquoise"},
{"id":8,"name":"ezima7","duration":8,"substance":"Aquamarine"},
{"id":9,"name":"apepler8","duration":66,"substance":"Teal"},
{"id":10,"name":"mharbard9","duration":62,"substance":"Crimson"},
{"id":11,"name":"cpuddifera","duration":97,"substance":"Green"},
{"id":12,"name":"bwintersonb","duration":2,"substance":"Mauv"},
{"id":13,"name":"mcamilloc","duration":9,"substance":"Teal"},
{"id":14,"name":"mfulmend","duration":11,"substance":"Orange"},
{"id":15,"name":"kfredie","duration":19,"substance":"Red"},
{"id":16,"name":"ufitzjohnf","duration":75,"substance":"Orange"},
{"id":17,"name":"cdavidofskig","duration":46,"substance":"Blue"},
{"id":18,"name":"sclendennenh","duration":22,"substance":"Puce"},
{"id":19,"name":"ccowderayi","duration":61,"substance":"Mauv"},
{"id":20,"name":"crapierj","duration":25,"substance":"Yellow"},
{"id":21,"name":"cdouchek","duration":12,"substance":"Fuscia"},
{"id":22,"name":"hnunnl","duration":23,"substance":"Violet"},
{"id":23,"name":"jkopjem","duration":43,"substance":"Goldenrod"},
{"id":24,"name":"jeverleyn","duration":91,"substance":"Orange"},
{"id":25,"name":"kosmento","duration":84,"substance":"Yellow"},
{"id":26,"name":"kbendsonp","duration":19,"substance":"Indigo"},
{"id":27,"name":"kderingq","duration":19,"substance":"Maroon"},
{"id":28,"name":"wfutcherr","duration":55,"substance":"Pink"},
{"id":29,"name":"sbengoecheas","duration":62,"substance":"Violet"},
{"id":30,"name":"obaldent","duration":17,"substance":"Indigo"},
{"id":31,"name":"pruddocku","duration":82,"substance":"Goldenrod"},
{"id":32,"name":"gbunneyv","duration":3,"substance":"Turquoise"},
{"id":33,"name":"pwillgressw","duration":92,"substance":"Indigo"},
{"id":34,"name":"hmccreathx","duration":82,"substance":"Aquamarine"},
{"id":35,"name":"bfeuelly","duration":60,"substance":"Crimson"},
{"id":36,"name":"jbeckersz","duration":90,"substance":"Puce"},
{"id":37,"name":"fgorstidge10","duration":54,"substance":"Purple"},
{"id":38,"name":"cgosnall11","duration":72,"substance":"Purple"},
{"id":39,"name":"cimmer12","duration":84,"substance":"Puce"},
{"id":40,"name":"gcaldes13","duration":88,"substance":"Puce"},
{"id":41,"name":"whickinbottom14","duration":43,"substance":"Khaki"},
{"id":42,"name":"prittmeier15","duration":59,"substance":"Turquoise"},
{"id":43,"name":"ishafier16","duration":80,"substance":"Aquamarine"},
{"id":44,"name":"lkrause17","duration":43,"substance":"Teal"},
{"id":45,"name":"lgraser18","duration":40,"substance":"Khaki"},
{"id":46,"name":"ccaghan19","duration":92,"substance":"Crimson"},
{"id":47,"name":"felecum1a","duration":19,"substance":"Maroon"},
{"id":48,"name":"blydall1b","duration":70,"substance":"Purple"},
{"id":49,"name":"htaplin1c","duration":32,"substance":"Indigo"},
{"id":50,"name":"smallinar1d","duration":97,"substance":"Maroon"},
{"id":51,"name":"mgrinin1e","duration":37,"substance":"Orange"},
{"id":52,"name":"idossit1f","duration":44,"substance":"Puce"},
{"id":53,"name":"kvaen1g","duration":10,"substance":"Teal"},
{"id":54,"name":"mjenkerson1h","duration":16,"substance":"Fuscia"},
{"id":55,"name":"okelsall1i","duration":29,"substance":"Blue"},
{"id":56,"name":"ecage1j","duration":46,"substance":"Pink"},
{"id":57,"name":"stwittey1k","duration":57,"substance":"Crimson"},
{"id":58,"name":"mwenzel1l","duration":47,"substance":"Maroon"},
{"id":59,"name":"gshropsheir1m","duration":88,"substance":"Maroon"},
{"id":60,"name":"omclae1n","duration":10,"substance":"Red"},
{"id":61,"name":"nheisham1o","duration":20,"substance":"Maroon"},
{"id":62,"name":"htwiname1p","duration":62,"substance":"Indigo"},
{"id":63,"name":"cconring1q","duration":12,"substance":"Goldenrod"},
{"id":64,"name":"drockey1r","duration":10,"substance":"Green"},
{"id":65,"name":"dcovino1s","duration":11,"substance":"Orange"},
{"id":66,"name":"smogridge1t","duration":65,"substance":"Violet"},
{"id":67,"name":"dshakesby1u","duration":14,"substance":"Teal"},
{"id":68,"name":"bgiovanitti1v","duration":25,"substance":"Crimson"},
{"id":69,"name":"ttrusler1w","duration":84,"substance":"Red"},
{"id":70,"name":"acollopy1x","duration":37,"substance":"Violet"},
{"id":71,"name":"dgoldbourn1y","duration":3,"substance":"Green"},
{"id":72,"name":"bbridgnell1z","duration":33,"substance":"Red"},
{"id":73,"name":"xgronous20","duration":9,"substance":"Orange"},
{"id":74,"name":"rfortoun21","duration":9,"substance":"Khaki"},
{"id":75,"name":"mbrinded22","duration":25,"substance":"Purple"},
{"id":76,"name":"cpercy23","duration":45,"substance":"Crimson"},
{"id":77,"name":"ehymers24","duration":57,"substance":"Green"},
{"id":78,"name":"jsorbie25","duration":39,"substance":"Blue"},
{"id":79,"name":"kshill26","duration":70,"substance":"Teal"},
{"id":80,"name":"gpedroli27","duration":46,"substance":"Puce"},
{"id":81,"name":"gjiruca28","duration":62,"substance":"Mauv"},
{"id":82,"name":"snibley29","duration":96,"substance":"Yellow"},
{"id":83,"name":"cdaine2a","duration":21,"substance":"Pink"},
{"id":84,"name":"kmoth2b","duration":48,"substance":"Aquamarine"},
{"id":85,"name":"cjarville2c","duration":49,"substance":"Mauv"},
{"id":86,"name":"ksarginson2d","duration":44,"substance":"Violet"},
{"id":87,"name":"cleefe2e","duration":26,"substance":"Crimson"},
{"id":88,"name":"cbursell2f","duration":62,"substance":"Maroon"},
{"id":89,"name":"cpamplin2g","duration":7,"substance":"Khaki"},
{"id":90,"name":"sgrisard2h","duration":76,"substance":"Fuscia"},
{"id":91,"name":"apetheridge2i","duration":6,"substance":"Pink"},
{"id":92,"name":"tsnel2j","duration":86,"substance":"Fuscia"},
{"id":93,"name":"fkrienke2k","duration":74,"substance":"Indigo"},
{"id":94,"name":"jcanniffe2l","duration":22,"substance":"Goldenrod"},
{"id":95,"name":"jpidcock2m","duration":88,"substance":"Puce"},
{"id":96,"name":"aminihan2n","duration":79,"substance":"Blue"},
{"id":97,"name":"gnimmo2o","duration":32,"substance":"Turquoise"},
{"id":98,"name":"cdavies2p","duration":10,"substance":"Orange"},
{"id":99,"name":"zalred2q","duration":80,"substance":"Khaki"},
{"id":100,"name":"mferron2r","duration":17,"substance":"Fuscia"}
]